### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'action')

### ISSUE THREAD

**Issue by affanshahid** [appthrust/moon-ci-retrospect#6]
I get the following error:

```
TypeError: Cannot read properties of undefined (reading 'action')
    at taskInfoOf (file:///home/runner/work/_actions/appthrust/moon-ci-retrospect/v1/index.js:4[6](https://github.com/Porchpass/porchpass-backend/actions/runs/10321751589/job/28575367202?pr=916#step:8:7):21)
    at main (file:///home/runner/work/_actions/appthrust/moon-ci-retrospect/v1/index.js:10:26)
    at async file:///home/runner/work/_actions/appthrust/moon-ci-retrospect/v1/index.js:133:5
```

**Comment by affanshahid** [comment]
Fixed by updating moon to 1.27.6
